name: Merge Request CI

on:
  push:
    branches: [ "develop-v3.5.2-ci-mr-test" ]
  pull_request:
    types: ["opened", "reopened"]
    branches: [ "develop-v3.5.2-ci" ]


jobs:

  Get-Stable-Branch:
    uses: tapdata/tapdata-application/.github/workflows/stable-branch.yml@main

  Build-And-Deploy:
    needs:
      - Get-Stable-Branch
    uses: tapdata/tapdata-application/.github/workflows/cicd-workflow.yml@main
    with:
      FRONTEND_BRANCH: ${{ needs.Get-Stable-Branch.outputs.FRONTEND_BRANCH }}
      ENTERPRISE_BRANCH: ${{ needs.Get-Stable-Branch.outputs.ENTERPRISE_BRANCH }}
      OPENSOURCE_BRANCH: ${{ needs.Get-Stable-Branch.outputs.OPENSOURCE_BRANCH }}
      LISENSE_BRANCH: "main"
      CONNECTOR_BRANCH: "main"
      ENTERPRISE_CONNECTOR_BRANCH: "ENTERPRISE_CONNECTOR_BRANCH"
      FRONTEND_MODE: "production"

    MRCI:
      runs-on: gcp-docker
      timeout-minutes: 60
      steps:
        - name: Check - If Push Action
          if: ${{ github.event_name == 'push' }}
          run: |
            echo "CURRENT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        - name: Check - If Merge Request Action
          if: ${{ github.event_name == 'pull_request' }}
          run: |
            echo "CURRENT_BRANCH=${{ github.ref }}" >> $GITHUB_ENV
        - name: Fetch Code - Main Repo
          uses: actions/checkout@v3
          with:
              fetch-depth: 0
              ref: ${{ env.CURRENT_BRANCH }}
              token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
              path: ./
        - name: Compile - IEngine And Management
          run: |
            #mvn clean install -DskipTests -P idaas -P not_encrypt -U -T1C
            echo "OK"
        - name: Run - Local Service
          run: |
            bash build/run_smoke_tests.sh
        - name: Test - Register Test Connector
          run: |
            echo "OK"
        - name: Test - E2E Qucik Test
          run: |
            echo "OK"
